{% set version = "1.2.6" %}

package:
  name: h3-pyspark
  version: {{ version }}

source:
  url: https://github.com/kevinschaich/h3-pyspark/archive/refs/tags/{{ version }}.tar.gz
  sha256: 8788b6179654515347949fac19b81bd5eedc2b7cc84a256a718669e1a37f2d3a

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - pytest
    - black
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - pyspark
    - h3-py
    - shapely

test:
  requires:
    - python {{ python_min }}
  imports:
    - h3_pyspark

about:
  home: https://github.com/kevinschaich/h3-pyspark
  summary: PySpark bindings for H3, a hierarchical hexagonal geospatial indexing system
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  dev_url: https://github.com/kevinschaich/h3-pyspark
  doc_url: https://github.com/kevinschaich/h3-pyspark

extra:
  recipe-maintainers:
    - kevinschaich
